### DISCUSSION TITLE
sudo generate-zbm fails

### DISCUSSION THREAD

**Discussion by sotiris-bos** [zbm-dev/zfsbootmenu#545] [Questions]
Hello, I am on Arch 6.6.2-arch1-1 using dracut.

I am trying to run generate-zbm but it fails with:

```
No initramfs generator specified; using dracut
Creating ZFSBootMenu 2.2.2 from kernel /boot/vmlinuz-linux
dracut: dracut module 'dbus-daemon' depends on 'systemd', which can't be installed
dracut: dracut module 'dbus' depends on 'dbus-daemon', which can't be installed
dracut: dracut module 'network-manager' depends on 'dbus', which can't be installed
dracut: dracut module 'network' depends on 'network-manager', which can't be installed
dracut: dracut module 'crypt-ssh' depends on 'network', which can't be installed
dracut: dracut module 'cifs' depends on 'network', which can't be installed
dracut: dracut module 'iscsi' depends on 'network', which can't be installed
dracut: dracut module 'nfs' depends on 'network', which can't be installed
dracut: dracut module 'crypt-ssh' cannot be found or installed.
Failed to create /tmp/ZCxVgMeAPf/zfsbootmenu.img
```

Here are the relevant config files:

```
cat /etc/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf 
nofsck="yes"
add_dracutmodules+=" zfsbootmenu "
omit_dracutmodules+=" btrfs zfs resume systemd systemd-initrd dracut-systemd plymouth dash "
```

```
cat /etc/zfsbootmenu/config.yaml 
Global:
  ManageImages: true
  BootMountPoint: /efi
  DracutConfDir: /etc/zfsbootmenu/dracut.conf.d
  PreHooksDir: /etc/zfsbootmenu/generate-zbm.pre.d
  PostHooksDir: /etc/zfsbootmenu/generate-zbm.post.d
#  InitCPIOConfig: /etc/zfsbootmenu/mkinitcpio.conf
Components:
  ImageDir: /efi/EFI/zbm
  Versions: 3
  Enabled: true
  syslinux:
    Config: /boot/syslinux/syslinux.cfg
    Enabled: false
EFI:
  ImageDir: /efi/EFI/zbm
  Versions: false
  Enabled: true
Kernel:
  CommandLine: ro quiet loglevel=0
```
