### DISCUSSION TITLE
How to run generate-zbm on debian? it is alway failed

### DISCUSSION THREAD

**Discussion by netherstar** [zbm-dev/zfsbootmenu#726] [Questions] [answered]
first i download ZBM source code, untar, cd into directory, run `make` and then `make install`, is it correct?
then i change config file, and run `generate-zbm` but it is alway show error.
i am using ZBM 3.0.1
```
root@pc /h/test# generate-zbm
Creating ZFSBootMenu 3.0.1 from kernel /boot/vmlinuz-6.1.0-31-amd64
Failed to create /tmp/tibQocefXn/zfsbootmenu.img
```

this is my /etc/zfsbootmenu/config.yml
```
Global:
  ManageImages: true
  InitCPIO: false
  BootMountPoint: /boot/efi
  DracutConfDir: /etc/zfsbootmenu/dracut.conf.d
  PreHooksDir: /etc/zfsbootmenu/generate-zbm.pre.d
  PostHooksDir: /etc/zfsbootmenu/generate-zbm.post.d
  InitCPIOConfig: /etc/zfsbootmenu/mkinitcpio.conf
Components:
  ImageDir: /boot/efi/EFI/zbm
  Versions: 3
  Enabled: true
EFI:
  ImageDir: /boot/efi/EFI/zbm
  Versions: false
  Enabled: false
  SplashImage: /etc/zfsbootmenu/splash.bmp
Kernel:
  CommandLine: ro quiet loglevel=0
```

and when i try to run command `dracut` or `dracut-core` not thing show
