### ISSUE TITLE
[Feature request] add a FilenamePrefix field under EFI in config.yaml

### ISSUE THREAD

**Issue by eoli3n** [zbm-dev/zfsbootmenu#264]
I'm dualbooting arch/void with zfsbootmenu.

On arch, I use LTS kernel, but not on void.
Both can build ZBM EFI image, I would them to have a filename which match.

On Arch:
- vmlinuz-linux-lts.EFI
- vmlinuz-linux-lts-backup.EFI

On Void:
- vmlinuz.EFI
- vmlinuz-backup.EFI

We can't force the EFI filename in the config file.
https://github.com/zbm-dev/zfsbootmenu/blob/master/etc/zfsbootmenu/config.yaml

Could you add a field ``FilenamePrefix`` ?
```yaml
EFI:
  ImageDir: /efi/EFI/ZBM
  FilenamePrefix: zbm
  Versions: false
  Enabled: true
```
Which will produce ``zbm.efi`` and ``zbm-backup.efi``.
