### ISSUE TITLE
zfsbootmenu loop

### ISSUE THREAD

**Issue by bobblkabb** [zbm-dev/zfsbootmenu#294]
I have installed according to the instructions [Void Linux Single disk syslinux MBR](https://github.com/zbm-dev/zfsbootmenu/wiki/Void-Linux----Single-disk-syslinux-MBR) (encrypted), but I end up in a loop in the zfsbootmenu. 
When I press return the timer starts again at 5s.
What could have gone wrong here?

**Comment by Dragon-debian** [comment]
does it import any pool?
whats wrote on screen?
press `Esc` and execute `zpool list`. does it show any imported pool?

**Comment by zdykstra** [comment]
There's only one 5 second loop in ZFSBootMenu, and that's when it can't import any pools. There's an option to drop to a recovery shell via the `escape` key. Once you're in the recovery shell please run `zpool import` and `zpool list` and relay exactly what the commands show.

**Comment by zdykstra** [comment]
Please reboot your system and tell me _exactly_ what countdown screen shows. We can go from there once you've confirmed the basics.

**Comment by bobblkabb** [comment]
> Please reboot your system and tell me _exactly_ what countdown screen shows. We can go from there once you've confirmed the basics.

I see the "Boot Menu".
There are a few entries in the meantime because I tried to fix it. So now I have
ZFSBootMenu 1.12.0_5
ZFSBootMenu 1.12.0_5
ZFSBootMenu 1.12.0_5
ZFSBootMenu 1.12.0_5

**Comment by bobblkabb** [comment]
> Please reboot your system and tell me _exactly_ what countdown screen shows. We can go from there once you've confirmed the basics.

I see the "Boot Menu".
There are a few entries in the meantime because I tried to fix it. So now I have
```
ZFSBootMenu 1.12.0_5
ZFSBootMenu 1.12.0_4
ZFSBootMenu 1.12.0_3
ZFSBootMenu 1.12.0_2
ZFSBootMenu 1.12.0_1
```

And on the bottom there's a timer counting from 5 to 0 over and over.

**Comment by zdykstra** [comment]
Okay, you're stuck in syslinux and not ZFSBootMenu. That's a completely different problem that is very difficult to debug. Does your system not support UEFI ?

**Comment by bobblkabb** [comment]
The laptop is a little older and I couldn't get UEFI work on it. System wasn't recognized, it always jumped to the next available boot option. Installed it a few times.
I installed the pre-build zfsbootmenu binary. refind-install gave me an error and suggested to rename refind_x64.efi to bootx64.efi, which I did. It also showed some efi variable errors. efivar-tester said it doesn't support efi variables or so. 
Fiddled with Bios settings (CSM -> enabled/disabled) but without success.

**Comment by bobblkabb** [comment]
There is only /boot/syslinux - nothing inside! So here's the problem!

Or did I do anything wrong to access the system?:

1. Boot hrmpf system from USB
2. zpool import -N -R /mnt zroot
zfs load-key -L prompt zroot
zfs mount zroot/ROOT/void
zfs mount zroot/home
3. mount -t proc proc /mnt/proc
mount -t sysfs sys /mnt/sys
mount -B /dev /mnt/dev
mount -t devpts pts /mnt/dev/pts
chroot /mnt /bin/bash

**Comment by zdykstra** [comment]
You wouldn't see a syslinux menu with ZFSBootMenu items in it if that were the case. You just need to mount the partition/filesystem that holds /boot/syslinux. Probably /dev/sda1.

**Comment by bobblkabb** [comment]
It's on sda1 - of course! 
Now I renamed, edited and checked but still the same behavior. 

Maybe I should try to install it on different hardware.

**Comment by Dragon-debian** [comment]
@bobblkabb
can you put the `config.yaml` content here?

**Comment by bobblkabb** [comment]
config.yaml:
```
Global:
  ManageImages: true
  BootMountPoint: /boot/syslinux
  DracutConfDir: /etc/zfsbootmenu/dracut.conf.d
  PreHooksDir: /etc/zfsbootmenu/generate-zbm.pre.d
  PostHooksDir: /etc/zfsbootmenu/generate-zbm.post.d
Components:
  ImageDir: /boot/syslinux/zbm
  Versions: 3
  Enabled: true
  syslinux:
    Config: /boot/syslinux/syslinux.cfg
    Enabled: true
EFI:
  ImageDir: /boot/efi/EFI/void
  Versions: false
  Enabled: false
Kernel:
  CommandLine: ro quiet loglevel=0
```
