### ISSUE TITLE
dracut fails to boot

### ISSUE THREAD

**Issue by camj2** [zbm-dev/zfsbootmenu#690]
### ZFSBootMenu build source

Local build, dracut

### ZFSBootMenu version

2.3.0

### Boot environment distribution

Void Linux

### Problem description

Building zfsbootmenu with dracut results in a kernel panic when attempting to boot. See below:

![screenshot](https://github.com/user-attachments/assets/a7b64de2-4004-464e-bb3a-ea33f6bb601f)

### Steps to reproduce

Here is my config file:

```
Global:
  ManageImages: true
  InitCPIO: false
  PreHooksDir: /etc/zfsbootmenu/generate-zbm.pre.d
  PostHooksDir: /etc/zfsbootmenu/generate-zbm.post.d
Components:
  Enabled: false
EFI:
  Enabled: true
  Versions: false
  ImageDir: /boot/efi/EFI/zbm
Kernel:
  CommandLine: quiet loglevel=0 zbm.show zbm.sort_key=creation zbm.skip_hooks=20-console-autosize.sh video=efifb:1920x1080
```

Changing `InitCPIO` to `true` and thus building with mkinitcpio works fine. This is a dracut specific issue.
