### ISSUE TITLE
Use of uninitialized value $namever in concatenation (.) or string at /usr/bin/generate-zbm line 614.

### ISSUE THREAD

**Issue by maanloper** [zbm-dev/zfsbootmenu#703]
### ZFSBootMenu build source

Local build, dracut

### ZFSBootMenu version

2.3.0

### Boot environment distribution

Ubuntu Server 24.04

### Problem description

I get these two (equal) warnings/errors when doing `generate-zbm`:
Use of uninitialized value $namever in concatenation (.) or string at /usr/bin/generate-zbm line 614.
Use of uninitialized value $namever in concatenation (.) or string at /usr/bin/generate-zbm line 614.

The initram and vmlinuz do get generated and are booting just fine:
```
-rwxr-xr-x 1 root root 98776148 Jan  9 14:11 initramfs-2.3.0_1.img
-rwxr-xr-x 1 root root 97663997 Jan  9 14:59 initramfs-2.3.0_2.img
-rwxr-xr-x 1 root root 97662519 Jan  9 18:34 initramfs-2.3.0_3.img
-rwxr-xr-x 1 root root 97662084 Jan  9 19:04 initramfs-2.3.0_4.img
-rwxr-xr-x 1 root root 14969224 Jan  9 14:11 vmlinuz-2.3.0_1
-rwxr-xr-x 1 root root 14969224 Jan  9 14:59 vmlinuz-2.3.0_2
-rwxr-xr-x 1 root root 14969224 Jan  9 18:34 vmlinuz-2.3.0_3
-rwxr-xr-x 1 root root 14969224 Jan  9 19:04 vmlinuz-2.3.0_4
```

YAML:
```
Global:
  ManageImages: true
  BootMountPoint: /boot/efi
  DracutConfDir: /etc/zfsbootmenu/dracut.conf.d
  PreHooksDir: /etc/zfsbootmenu/generate-zbm.pre.d
  PostHooksDir: /etc/zfsbootmenu/generate-zbm.post.d
  InitCPIOConfig: /etc/zfsbootmenu/mkinitcpio.conf
Components:
  ImageDir: /boot/efi/EFI/ZBM
  Versions: 5
  Enabled: true
EFI:
  ImageDir: /boot/efi/EFI/ZBM
  Versions: 5
  Enabled: false
Kernel:
  CommandLine: ro quiet loglevel=0
```

Code snippet of relevant lines in `/usr/bin/generate-zbm`:
```
 612   # If only one is defined, that's the version
 613   unless ( nonempty $filever ) {
 614     Log("No version found in kernel strings, using $namever from path $kernel");
 615     return $namever;
 616   }
```

### Steps to reproduce

Run `generate-zbm`
